apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: chirpstack-network-server
  name: chirpstack-network-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chirpstack-network-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: chirpstack-network-server
    spec:
      containers:
        - env:
            - name: JOIN_SERVER__DEFAULT__SERVER
              value: http://chirpstack-application-server:8003
            - name: NETWORK_SERVER__BAND__NAME
              value: US_902_928
            - name: NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER
              value: tcp://mosquitto:1883
            - name: POSTGRESQL__DSN
              value: postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable
            - name: REDIS__URL
              value: redis://redis:6379
          image: chirpstack/chirpstack-network-server:3
          name: chirpstack-network-server
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
